### ISSUE TITLE
Need a way to get jsonResponse 

### ISSUE THREAD

**Issue by sakshyamdahal** [sakshyamdahal/live-chair-android#1]
check out class GetBarbersTask which is in BarberListActivity.java

**Comment by eddiem3** [comment]
V1 has a barbers endpoint

**Comment by sakshyamdahal** [comment]
yeaah

**Comment by eddiem3** [comment]
What's the issue?

On Saturday, February 7, 2015, Sakshyam Dahal notifications@github.com
wrote:

> yeaah
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sakshyamdahal/live-chair-android/issues/1#issuecomment-73374650
> .

## 

Eddie Massey III

Artificial Intelligence in Action Founder
Low Country Judicial Merit Selection Committee

803-290-2238
eddiemassey@ai-inaction.org
eddiemassey.com

**Comment by sakshyamdahal** [comment]
// data given, progress data and return data from background operation
    class GetBarbersTask extends AsyncTask<Object, Void, JSONArray> {

```
    JSONArray jsonResponse;


    @Override
    protected JSONArray doInBackground(Object[] params) {
```

//
//            int responseCode = -1;
//
//            // try getting the barber data
//            try {
//                URL barberListUrl = new URL("https://api.forecast.io/forecast/5534ffc4c4805ecb5a7800e9be7bbe27/37.8267,-122.423");
//                HttpURLConnection connection = (HttpURLConnection) barberListUrl.openConnection();
//
//                connection.connect();
//                responseCode = connection.getResponseCode();
//
//
//                if (responseCode == HttpURLConnection.HTTP_OK)
//                {
//                    InputStream inputStream = connection.getInputStream();
//
//                    Log.i(TAG, "InputStream " + inputStream);
//
//                    Reader reader = new InputStreamReader(inputStream);
//
//                    int contentLength = connection.getContentLength();
//
//                    Log.i(TAG, contentLength + "");
//                    char[] charArray = new char[contentLength];
//
//
//
//                    reader.read(charArray);
//                    String responseData = new String(charArray);
//
//
//                    jsonResponse = new JSONArray(responseData);
//                    Log.v(TAG, jsonResponse.toString());
//
//                }
//                else {
//                    Log.i(TAG, "Unsuccessful HTTP Response Code" + responseCode);
//                }
//            } catch (MalformedURLException e) {
//                Log.e(TAG, "Exection caught: " + e);
//            }
//            catch (IOException e)
//            {
//                Log.e(TAG, "Exception caught: " + e);
//            }
//            catch (Exception e)
//            {
//                Log.e(TAG, "Exception caught: " + e);
//            }
//
//            return jsonResponse;
//        }
    //}

```
        String barberUrl = "https://fathomless-temple-1065.herokuapp.com/api/v1/users/barbers";

        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder().url(barberUrl).build();

        Call call = client.newCall(request);
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {

                    }
                });
            }

            @Override
            public void onResponse(Response response) throws IOException {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {

                    }
                });
                try {
                    final String jsonData = response.body().string();
                    //Log.i(TAG, jsonData);

                    if (response.isSuccessful()) {
                        jsonResponse = new JSONArray(jsonData);
                        Log.i("json success", jsonResponse.toString());



                     for (int i = 0; i < jsonResponse.length(); i++)
                        {
                            JSONObject array = jsonResponse.getJSONObject(i);
                            JSONObject barbers = array.getJSONObject("user");
                            String name = barbers.getString("fname");
                            Log.i(TAG, name);
                        }

                    }

                }
                catch (IOException e) {

                }
                catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        });

        return jsonResponse;

   }

    @Override
    // is on user interface
    protected void onPostExecute(JSONArray result)
    {
        mBarberData = result;
        //Log.i("i am here", mBarberData.toString());
        updateList();
    }

}
```

**Comment by sakshyamdahal** [comment]
ignore the comments.. the function onPostExecute has a input result which is the output of method doInBackground.. the issue is that i am not getting a correct result.. i get null instead of jsonArray which i should be getting to update the views.

**Comment by eddiem3** [comment]
What response code do you get back?

On Saturday, February 7, 2015, Sakshyam Dahal notifications@github.com
wrote:

> ignore the comments.. the function onPostExecute has a input result which
> is the output of method doInBackground.. the issue is that i am not getting
> a correct result.. i get null instead of jsonArray which i should be
> getting to update the views.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sakshyamdahal/live-chair-android/issues/1#issuecomment-73374845
> .

## 

Eddie Massey III

Artificial Intelligence in Action Founder
Low Country Judicial Merit Selection Committee

803-290-2238
eddiemassey@ai-inaction.org
eddiemassey.com

**Comment by sakshyamdahal** [comment]
I figured it out. Thankx.
